### ISSUE TITLE
swirl 2.4

### ISSUE THREAD

**Issue by seankross** [swirldev/swirl#372]
- [x] Multi-language support
- [x] Add #300 from @wush978
- [x] New function: `install_course()` & `.swc` compatibility
- [x] Integration with new Coursera grading API
- [x] Callback integration for logging and grading 
- [x] Fix `testit`/`demo_lesson` problem in `swirl.R`
- [x] Handle where user progress and logs are saved
- [x] Provide a function for finding files included in lessons
- [x] Add `force` argument to `install_course()`

**Comment by seankross** [comment]
Troublesome questions:

```yaml
- Class: text_question
  Output: "What are the genotypes you can have and have blood type A."
  CorrectAnswer: "AA AO"
  AnswerTests: any_of_exprs("AA AO","AO AA")
  Hint: hint
```

And multiple right answers for multiple choice questions.
