### ISSUE TITLE
swirl 2.5

### ISSUE THREAD

**Issue by seankross** [swirldev/swirl#407]
- [ ] [Add](https://developers.credly.com/) [badges](https://wiki.mozilla.org/Badges)
- [ ] Add "viewer pane" questions

**Comment by seankross** [comment]
Troublesome questions:

```yaml
- Class: text_question
  Output: "What are the genotypes you can have and have blood type A."
  CorrectAnswer: "AA AO"
  AnswerTests: any_of_exprs("AA AO","AO AA")
  Hint: hint
```

And multiple right answers for multiple choice questions.
