### ISSUE TITLE
setwd("..") doubled effect

### ISSUE THREAD

**Issue by jsansen** [swirldev/swirl#880]
Hi, 
first thanks for all the swirl concept and work !

I'm building a course and get an issue I can't find any answers or idea of a solution about, It seems to be swirl related as it doesn't happen on R console outside of a swirl course. 

So, I'm working on a working directory course, and want the student to try the setwd("..") command. I ask to do these commands:

```r
setwd("test_dir")
setwd("..")
setwd("test_dir")
```

The thing is, when I'm performing the command setwd(".."), it actually is doing setwd(".. /..") i.e. a double "get back" ( getting not one folder upward in the tree but two folders), and consequently, the second setwd("test_dir") can't work..

```r
setwd("test_dir")
getwd()

[1] "C:/Users/JS/R/test_dir"

setwd("..")
getwd()

[1] "C:/Users/JS"

setwd("test_dir")
```

I just don't understand where it comes from as my yaml file seems ok:

```yaml
- Class: cmd_question
  Output: here goes my speech about the role of ".."
  CorrectAnswer: setwd("..")
  AnswerTests: any_of_exprs('setwd("..")', 'setwd("../")', 'setwd("./..")','setwd("./../")')
  Hint: here some hints about what to do

- Class: cmd_question
  Output: second question to get back to test_dir
  CorrectAnswer: setwd("test_dir/")
  AnswerTests: any_of_exprs('setwd("test_dir")', 'setwd("test_dir/")', 'setwd("./test_dir")','setwd("./test_dir/")')
  Hint: another hint
```
any idea ?
in advance, thanks for the help !
